//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbstractBidding
    {
        public int ReviewerId { get; set; }
        public int AbstractId { get; set; }
    
        public virtual Reviewer Reviewer { get; set; }
        public virtual Abstract Abstract { get; set; }
    }
}
