//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenceManagerContainer : DbContext
    {
        public ConferenceManagerContainer()
            : base("name=ConferenceManagerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conference> ConferenceSet { get; set; }
        public virtual DbSet<Session> SessionSet { get; set; }
        public virtual DbSet<Listener> ListenerSet { get; set; }
        public virtual DbSet<Abstract> AbstractSet { get; set; }
        public virtual DbSet<Paper> PaperSet { get; set; }
        public virtual DbSet<PaperReview> PaperReviewSet { get; set; }
        public virtual DbSet<AbstractBidding> AbstractBiddingSet { get; set; }
    }
}
